---
title: "Homework 1 - Dates and Time"
author: "Johnson ODEJIDE"
date: "2023-01-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lubridate)
library(tidyverse)
library(nycflights13)
```

## 1
```{r}
first_date <- ymd("2020-06-06")
second_date <- ymd("2021-07-14")

# Number of days
(first_date %--% second_date) %/% days(1)
```


## 2
```{r}
leap_year(1988)
```


## 3
```{r}
leap_year(1989)
```


## 4
Months would have differing results when expressed in form of time because there are differing numbers of days in a month, some months have 30 days, others have 31 days, yet a month like February has 28 days (and 29 days in a leap year).


## 5

```{r}
john_bday <- ymd("1962-04-11")
(john_bday %--% today()) %/% years(1)
```

## 6

```{r}
make_datetime_100 <- function(year, month, day, time) {
  make_datetime(year, month, day, time %/% 100, time %% 100)
}

flights_dt <- flights %>% 
  filter(!is.na(dep_time), !is.na(arr_time)) %>% 
  mutate(
    dep_time = make_datetime_100(year, month, day, dep_time),
    arr_time = make_datetime_100(year, month, day, arr_time),
    sched_dep_time = make_datetime_100(year, month, day, sched_dep_time),
    sched_arr_time = make_datetime_100(year, month, day, sched_arr_time)
  ) %>% 
  select(origin, dest, carrier, arr_time, dep_time)
  
flights_dt 
```

## 7
```{r}
flights_dt %>% 
  filter(
    !is.na(dep_time),
    year(dep_time) == 2013, 
    month(dep_time) >= 4 & month(dep_time) <= 10) -> lights_dt_filt

lights_dt_filt %>% 
  ggplot(aes(dep_time)) +
  geom_freqpoly(bins = 94) +
  scale_y_continuous(breaks = seq(0, 2500, by = 500))
```


## 8

```{r}
flights_AA <- flights_dt %>% 
  filter(origin == "LGA",
         dest == "DFW",
         carrier == "AA") %>% 
  select(-dep_time) %>% 
  slice(115:125) %>% 
  arrange(arr_time)
flights_AA
```

## 9
```{r}
flights_AA %>% 
  select(arr_time) %>% 
  head(2) %>% 
  mutate(arr_time = as_datetime(arr_time)) -> flights_AA_2

dminutes(flights_AA_2[2, 1] - flights_AA_2[1, 1])

```
